version: 2

sources:
  - name: raw
    schema: raw_data_circle
    description: circle data
    tables:

    - name: parcel
      identifier: raw_cc_parcel
      description: parcels illoooo
      columns:
          - name: Parcel_id
          - name: Parcel_tracking
          - name: Transporter
          - name: Priority
          - name: Date_purCHase
          - name: Date_sHIpping
          - name: DATE_delivery
          - name: DaTeCANcelled

    - name: product
      description: raw_cc_parcel_product
      columns:
          - name: PaRCEL_id
          - name: Model_mAME
          - name: QUANTITY