version: 2

sources:
  - name: raw
    schema: raw_data_circle
    description: circle data
    tables:

    - name: parcel
      identifier: raw_cc_parcel
      description: parcels illoooo
      columns:
          - name: Parcel_id
          - name: Parcel_tracking
          - name: Transporter
          - name: Priority
          - name: Date_purCHase
          - name: Date_sHIpping
          - name: DATE_delivery
          - name: DaTeCANcelled

    - name: product
      identifier: raw_cc_parcel_product
      description: productos illoooo
      columns:
          - name: PaRCEL_id
          - name: Model_mAME
          - name: QUANTITY

models:
  - name: cc_parcel
    columns:
      - name: parcel_id
        tests:
            - not_null
      - name: parcel_tracking
      - name: transporter
      - name: priority
      - name: date_purchase
      - name: date_shipping
      - name: date_delivery
      - name: date_cancelled
      - name: month_purchase
      - name: status
      - name: expedition_time
      - name: transport_time
      - name: delivery_time
      - name: delay
      - name: quantity
      - name: model_name

  - name: cc_parcel_products
    columns:
      - name: parcel_id
        tests:
            - not_null
      - name: model_name
      - name: parcel_tracking
      - name: transporter
      - name: priority
      - name: date_purchase
      - name: date_shipping
      - name: date_delivery
      - name: date_cancelled
      - name: month_purchase
      - name: status
      - name: expedition_time
      - name: transport_time
      - name: delivery_time
      - name: delay
      - name: quantity